/* Alfa Labs HSE shared access + targeted dashboard stability fixes */
(function(){'use strict';if(window.__ALFA_AUTH__)return;window.__ALFA_AUTH__=true;
const CONFIG={allowedDomain:'@alfalabs.com',users:[{email:'hossam.elsharabasy@alfalabs.com',role:'admin'},{email:'mohamed.nasr@alfascan.com',role:'viewer',expiresAt:1789774860000}],sessionKey:'alfaLabsAuthSession'};
const getSession=()=>{try{return JSON.parse(sessionStorage.getItem(CONFIG.sessionKey)||'null')}catch(e){return null}},clearSession=()=>sessionStorage.removeItem(CONFIG.sessionKey);
function isAllowed(email){const e=String(email||'').trim().toLowerCase(),u=CONFIG.users.find(x=>x.email.toLowerCase()===e);return !!u&&(!u.expiresAt||Date.now()<u.expiresAt)&&(e.endsWith(CONFIG.allowedDomain)||e==='mohamed.nasr@alfascan.com')}
function setSession(email,role){const u=CONFIG.users.find(x=>x.email.toLowerCase()===String(email||'').trim().toLowerCase());sessionStorage.setItem(CONFIG.sessionKey,JSON.stringify({email,role,loginAt:Date.now(),expiresAt:u?.expiresAt||null}))}
function guard(){if((location.pathname.split('/').pop()||'index.html').toLowerCase()==='login.html')return true;const s=getSession();if(!s||!isAllowed(s.email)||(s.expiresAt&&Date.now()>=s.expiresAt)){clearSession();location.replace('./login.html?return='+encodeURIComponent(location.href));return false}document.documentElement.dataset.alfaRole=s.role;document.body.dataset.alfaRole=s.role;return true}
function toast(msg){let t=document.getElementById('alfa-auth-toast');if(!t){t=document.createElement('div');t.id='alfa-auth-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function viewerLock(){const s=getSession();if(!s||s.role==='admin')return;document.addEventListener('click',e=>{const t=e.target.closest('button,a,[role="button"]');if(t&&/(export|download|print|copy|save report|get a report|تحميل|تنزيل|طباعة|نسخ|تقرير)/i.test(t.innerText||t.title||'')){e.preventDefault();e.stopPropagation();toast('View-only access — this action is restricted.')}},true);document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('copy',e=>e.preventDefault());document.addEventListener('cut',e=>e.preventDefault());document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&['c','x','s','p','u'].includes(e.key.toLowerCase()))e.preventDefault()},true)}
function addBadge(){const s=getSession();if(!s||document.getElementById('alfa-user-badge'))return;const host=document.querySelector('.unified-meta,.header-actions,.user')||document.body,el=document.createElement('div');el.id='alfa-user-badge';el.style.cssText='display:flex;align-items:center;gap:8px;direction:ltr';el.innerHTML='<b>'+(s.role==='admin'?'ADMIN':'VIEW ONLY')+'</b><span>'+s.email.split('@')[0]+'</span><button id="alfa-logout" type="button">Logout</button>';host.appendChild(el);el.querySelector('button').onclick=()=>{clearSession();location.replace('./login.html')}}
function init(){if(!guard())return;viewerLock();addBadge()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.AlfaHSEAuth={CONFIG,getSession,setSession,clearSession,isAllowed,roleFor:e=>CONFIG.users.find(x=>x.email.toLowerCase()===String(e||'').trim().toLowerCase())?.role||null,guard,toast};})();
/* Home: recover CAPA charts/KPIs and remove malformed inline-code text leaked into the page. */
(function(){const p=location.pathname.toLowerCase();if(!(p==='/'||p.endsWith('/index.html')||p.endsWith('/alfa-labs-hse-dashboard/')))return;
const n=v=>String(v??'').normalize('NFKC').replace(/[\u064B-\u065F\u0670\u0640]/g,'').toLowerCase(),risk=v=>{const s=n(v);return s.includes('critical')||s.includes('حرج')?'Critical':s.includes('high')||s.includes('عالي')?'High':s.includes('medium')||s.includes('متوسط')?'Medium':s.includes('low')||s.includes('منخفض')?'Low':''},status=v=>{const s=n(v);return s.includes('progress')||s.includes('تنفيذ')?'In Progress':s.includes('open')||s.includes('مفتوح')?'Open':s.includes('closed')||s.includes('مغلق')?'Closed':''},fmt=v=>Number(v||0).toLocaleString('en-US'),put=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=fmt(v)};
function cleanLeaked(){const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),del=[];let x;while((x=w.nextNode())){if(x.parentElement?.closest('script,style,noscript,textarea,code,pre'))continue;const t=(x.nodeValue||'').trim();if(t.length>220&&(/function\s+norm\s*\(/i.test(t)||/function\s+riskKey\s*\(/i.test(t)||(/chart\.innerHTML/i.test(t)&&/riskChart/i.test(t))||(/const\s+c\s*=\s*\{\s*Critical/i.test(t)&&/In Progress/i.test(t)))&&(/=>|function|\.includes\(|\.innerHTML|document\.getElementById/i.test(t)))del.push(x)}del.forEach(x=>x.parentNode&&x.parentNode.removeChild(x))}
async function restore(){try{const r=await fetch('./capa-data.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(!Array.isArray(d))throw Error('Invalid CAPA JSON');const c={Critical:0,High:0,Medium:0,Low:0,Open:0,'In Progress':0,Closed:0};d.forEach(x=>{const a=risk(x.risk),b=status(x.status);if(a)c[a]++;if(b)c[b]++});[['totalValue',d.length],['criticalValue',c.Critical],['highValue',c.High],['openValue',c.Open],['progressValue',c['In Progress']],['closedValue',c.Closed],['donutTotal',d.length],['legendOpen',c.Open],['legendProgress',c['In Progress']],['legendClosed',c.Closed],['actionCritical',c.Critical],['actionHigh',c.High],['actionOpen',c.Open]].forEach(([id,v])=>put(id,v));const ch=document.getElementById('riskChart');if(ch){const m=Math.max(c.Critical,c.High,c.Medium,c.Low,1);ch.innerHTML=['Critical','High','Medium','Low'].map(k=>'<div class="bar-wrap"><div class="bar-value">'+fmt(c[k])+'</div><div class="bar '+k.toLowerCase()+'" style="height:'+Math.max(4,c[k]/m*88)+'%"></div><div class="bar-label">'+k+'</div></div>').join('')}const total=d.length,a=total?c.Open/total*100:0,b=total?c['In Progress']/total*100:0,don=document.getElementById('statusDonut');if(don)don.style.background='conic-gradient(#315d91 0 '+a+'%,#d97722 '+a+'% '+(a+b)+'%,#23834b '+(a+b)+'% 100%)';const sr=document.getElementById('statusRate');if(sr)sr.textContent=total?Math.round(c.Closed/total*100)+'% closed':'—';const ds=document.getElementById('dataStatus');if(ds)ds.textContent='CAPA live data connected • '+fmt(total)+' records'}catch(e){console.error('[Home CAPA recovery]',e);const ds=document.getElementById('dataStatus');if(ds)ds.textContent='CAPA data unavailable — refresh or contact HSE admin'}}
const run=()=>{cleanLeaked();restore()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();window.addEventListener('load',()=>{cleanLeaked();restore()});setTimeout(cleanLeaked,300);setTimeout(cleanLeaked,1100);setTimeout(restore,1400);})();
/* HSE Teams: merge Raymond/ريمون aliases once in the rendered table and keep summary KPIs aligned. */
(function(){if(!location.pathname.toLowerCase().endsWith('/hse-teams.html'))return;const canon=s=>{const v=String(s||'').normalize('NFKC').replace(/[\u064B-\u065F\u0670\u0640]/g,'').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');return(v.includes('ريمون')||v.includes('raymond')||v.includes('raimond'))?'__raymond__':v},num=el=>Number((el?.textContent||'').replace(/[^\d.-]/g,''))||0;let busy=false;function merge(){if(busy)return;const body=document.getElementById('teamRows');if(!body)return;const trs=[...body.querySelectorAll('tr')].filter(tr=>tr.cells.length>2);if(!trs.length)return;busy=true;try{const map=new Map();trs.forEach(tr=>{const k=canon(tr.cells[1]?.textContent);if(!k)return;if(!map.has(k)){map.set(k,tr);return}const keep=map.get(k);for(let i=2;i<Math.min(keep.cells.length,tr.cells.length);i++){const cell=keep.cells[i],target=cell.querySelector('.pill')||cell;target.textContent=(num(cell)+num(tr.cells[i])).toLocaleString('en-US')}tr.remove()});const sel=document.getElementById('memberSelect');if(sel){const seen=new Set();[...sel.options].slice(1).forEach(o=>{const k=canon(o.textContent);if(seen.has(k))o.remove();else seen.add(k)})}const left=[...body.querySelectorAll('tr')].filter(tr=>tr.cells.length>2),totals={};left.forEach(tr=>{for(let i=2;i<Math.min(8,tr.cells.length);i++)totals[i]=(totals[i]||0)+num(tr.cells[i])});[['memberCount',left.length],['trainedCount',totals[2]||0],['capaCount',totals[4]||0],['openCount',totals[5]||0],['closedCount',totals[7]||0]].forEach(([id,v])=>{const el=document.getElementById(id);if(el)el.textContent=Number(v).toLocaleString('en-US')});const tc=document.getElementById('tableCount');if(tc)tc.textContent=left.length+' team members'}finally{busy=false}}const start=()=>{merge();const b=document.getElementById('teamRows');if(b)new MutationObserver(merge).observe(b,{childList:true,subtree:true})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();})();