/* Alfa Labs HSE — Global UI Standard: Dark/Light + Arabic/English + responsive */
(function(){
'use strict';
if(window.__ALFA_GLOBAL_UI__)return;window.__ALFA_GLOBAL_UI__=true;
const M={
Home:'الرئيسية',MAIN:'الرئيسية',SYSTEM:'النظام',Training:'التدريب',Safety Observations:'ملاحظات السلامة',Incidents:'الحوادث',Near Miss:'شبه الحوادث',Inspections:'التفتيشات',Fire Safety:'سلامة الحريق',First Aid:'الإسعافات الأولية',Analytics:'التحليلات',Reports:'التقارير',Settings:'الإعدادات',
'HSE Management Dashboard':'لوحة إدارة السلامة والصحة المهنية والبيئة','Alfa Labs HSE Management Platform':'منصة ألفا لابز لإدارة السلامة والصحة المهنية والبيئة','Alfa Labs • HSE Platform':'ألفا لابز • منصة السلامة والصحة المهنية والبيئة','Last updated today':'آخر تحديث اليوم',
'Executive HSE Overview':'نظرة تنفيذية على أداء HSE','CAPA performance and Training activity in one clear management view.':'أداء CAPA ونشاط التدريب في لوحة إدارية واضحة.','LIVE DATA • ALFA LABS':'بيانات مباشرة • ألفا لابز','HSE Performance 👋':'أداء HSE 👋','Key indicators and management actions at a glance':'المؤشرات الرئيسية وإجراءات الإدارة في نظرة واحدة','HSE PERFORMANCE — LIVE':'أداء HSE — مباشر',
'Total CAPA':'إجمالي CAPA','Open CAPA':'CAPA المفتوحة','High Risk':'مخاطر عالية','Critical':'حرج','Training Sessions':'جلسات التدريب','Training Hours':'ساعات التدريب','All CAPA records':'جميع سجلات CAPA','Requires corrective action':'تتطلب إجراءً تصحيحياً','Priority CAPA':'CAPA ذات الأولوية','Management attention':'تحتاج اهتمام الإدارة','Actual dated records':'السجلات المؤرخة','Recorded training hours':'ساعات التدريب المسجلة','View CAPA →':'عرض CAPA ←','Filter Open →':'تصفية المفتوحة ←','Filter High →':'تصفية العالية ←','Filter Critical →':'تصفية الحرجة ←','View Training →':'عرض التدريب ←','Training analytics →':'تحليلات التدريب ←',
'CAPA Risk Profile':'ملف مخاطر CAPA','Current distribution':'التوزيع الحالي','CAPA Status':'حالة CAPA','Live':'مباشر','Open':'مفتوحة','In Progress':'قيد التنفيذ','Closed':'مغلقة','Training Trend':'اتجاه التدريب','Sessions by month':'الجلسات حسب الشهر','Training Mix':'توزيع التدريب','Top training types':'أعلى أنواع التدريب','Action Required':'إجراء مطلوب','Priority management view':'عرض الإدارة حسب الأولوية','Immediate management attention':'اهتمام إداري فوري','Priority corrective action':'إجراء تصحيحي ذو أولوية','Still requiring closure':'ما زال يتطلب الإغلاق',
'Employees trained':'الموظفون المدربون','Departments covered':'الإدارات المشمولة','Training programs':'البرامج التدريبية','Training providers':'جهات التدريب','Add CAPA':'إضافة CAPA','Get a Report':'الحصول على تقرير',
'CAPA — Management Analysis':'CAPA — التحليل الإداري','Same dashboard visual language | management-level CAPA profile':'نفس الهوية البصرية للوحة | تحليل CAPA على مستوى الإدارة','CAPA — Detailed Distribution':'CAPA — التوزيع التفصيلي','Additional management breakdown | same live CAPA dataset':'تفصيل إداري إضافي | نفس بيانات CAPA المباشرة','CAPA Records by Month':'سجلات CAPA حسب الشهر','Top CAPA Sites':'أعلى مواقع CAPA','CAPA by Governorate':'CAPA حسب المحافظة','Top CAPA Owners':'أعلى مسؤولي CAPA',
'Training — Management Analysis':'التدريب — التحليل الإداري','Same dashboard visual language | training coverage and delivery':'نفس الهوية البصرية للوحة | تغطية وتنفيذ التدريب','Management Summary & Actions':'الملخص الإداري والإجراءات','Executive reference | generated directly from live dashboard data':'مرجع تنفيذي | مُنشأ مباشرة من بيانات اللوحة','Executive Highlights':'أبرز النتائج التنفيذية','Management Actions':'الإجراءات الإدارية',
'Prioritize Critical and High CAPA closure.':'إعطاء أولوية لإغلاق CAPA الحرجة والعالية.','Review open CAPA ageing and overdue ownership.':'مراجعة أعمار CAPA المفتوحة والمسؤوليات المتأخرة.','Maintain monthly training coverage by department.':'الحفاظ على تغطية التدريب الشهرية حسب الإدارة.','Use site and department filters for targeted follow-up.':'استخدام مرشحات الموقع والإدارة للمتابعة المستهدفة.',
'Training Management':'إدارة التدريب','Training Record & HSE Training Analytics':'سجلات التدريب وتحليلات HSE','Training Management & Analytics':'إدارة التدريب والتحليلات','Analyze the complete Training Record using Year, Month, From Date and To Date filters.':'تحليل سجل التدريب باستخدام مرشحات السنة والشهر ومن تاريخ وإلى تاريخ.','Time Filters':'مرشحات الوقت','Year':'السنة','All Years':'كل السنوات','Month':'الشهر','All Months':'كل الشهور','January':'يناير','February':'فبراير','March':'مارس','April':'أبريل','May':'مايو','June':'يونيو','July':'يوليو','August':'أغسطس','September':'سبتمبر','October':'أكتوبر','November':'نوفمبر','December':'ديسمبر','From Date':'من تاريخ','To Date':'إلى تاريخ','Apply Filters':'تطبيق المرشحات','Reset':'إعادة تعيين',
'Employees Trained':'الموظفون المدربون','Departments':'الإدارات','Training Programs':'البرامج التدريبية','Training Providers':'جهات التدريب','Employee Status':'حالة الموظف','Training Type':'نوع التدريب','Department':'الإدارة','Job Title':'المسمى الوظيفي','Training Program':'البرنامج التدريبي','Training Provider':'جهة التدريب','Site':'الموقع','Governorate':'المحافظة','City':'المدينة','Area':'المنطقة','Lab Code':'كود المعمل','Training Records':'سجلات التدريب','records':'سجلات','Training Type 2':'نوع التدريب 2','Duration (Hours)':'المدة (بالساعات)','Trainer Notes':'ملاحظات المدرب','Trainer Name':'اسم المدرب','Training Date':'تاريخ التدريب','Employee ID':'الرقم الوظيفي','Employee Name':'اسم الموظف','Provider':'جهة التدريب','Area Name':'اسم المنطقة','Site Name':'اسم الموقع',
'CAPA Records':'سجلات CAPA','CAPA Management':'إدارة CAPA','CAPA Filters':'مرشحات CAPA','Search':'بحث','Clear':'مسح','Save CAPA':'حفظ CAPA','Cancel':'إلغاء','Select':'اختيار','Due Date':'تاريخ الاستحقاق','Risk Severity':'درجة المخاطر','Status':'الحالة','Observation':'الملاحظة','Hazards Types':'أنواع المخاطر','Hazard Details':'تفاصيل الخطر','Corrective Action':'الإجراء التصحيحي','Owner':'المسؤول','Code':'الكود','Site License':'ترخيص الموقع','HSE Responsibility':'مسؤولية HSE',
'Safety First • Safety Is Everyone’s Responsibility':'السلامة أولاً • السلامة مسؤولية الجميع','Created':'تم الإنشاء','Created by Hossam Elsharabasy — HSE Manager':'تم الإنشاء بواسطة حسام الشراباسي — مدير HSE','Today':'اليوم'
};
const norm=s=>String(s??'').replace(/\s+/g,' ').trim(),orig=new WeakMap();
function tr(lang,root=document.body){
 const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement&&/^(SCRIPT|STYLE|CANVAS)$/.test(n.parentElement.tagName)?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}),a=[];
 while(w.nextNode())a.push(w.currentNode);
 a.forEach(n=>{let r=orig.has(n)?orig.get(n):n.nodeValue;if(!orig.has(n))orig.set(n,r);let k=norm(r);if(!k||/^[-–—•·\d\s,.:/()+%]+$/.test(k))return;if(M[k])n.nodeValue=lang==='ar'?M[k]:k});
 root.querySelectorAll('[placeholder],[title],[aria-label]').forEach(e=>['placeholder','title','aria-label'].forEach(x=>{let v=e.getAttribute(x),k=norm(v);if(v&&M[k])e.setAttribute(x,lang==='ar'?M[k]:k)}));
 root.querySelectorAll('option').forEach(e=>{let r=e.dataset.hseOriginal||(e.dataset.hseOriginal=e.textContent),k=norm(r);if(M[k])e.textContent=lang==='ar'?M[k]:k});
}
function charts(d){
 try{if(!window.Chart)return;Chart.defaults.color=d?'#d4e1ee':'#536579';Chart.defaults.borderColor=d?'#31465d':'#dce5ee';
 if(window.charts)Object.values(window.charts).forEach(c=>{if(!c)return;c.options.color=d?'#d4e1ee':'#536579';if(c.options.scales)Object.values(c.options.scales).forEach(s=>{s.ticks=s.ticks||{};s.ticks.color=d?'#cbd8e7':'#536579';s.grid=s.grid||{};s.grid.color=d?'rgba(255,255,255,.10)':'rgba(80,100,120,.12)'});if(c.options.plugins?.legend)c.options.plugins.legend.labels={...(c.options.plugins.legend.labels||{}),color:d?'#d4e1ee':'#536579'};c.update('none')})}catch(e){}
}
function theme(){let d=localStorage.getItem('alfaLabsTheme')==='dark';document.documentElement.classList.toggle('hse-dark',d);document.body.dataset.hseTheme=d?'dark':'light';let b=document.getElementById('hse-theme-btn');if(b)b.textContent=d?'☀️ Light':'🌙 Dark';charts(d);window.dispatchEvent(new CustomEvent('hseThemeChanged',{detail:{dark:d}}))}
function lang(){let l=localStorage.getItem('alfaLabsLang')||'en';document.documentElement.lang=l;document.documentElement.dir=l==='ar'?'rtl':'ltr';document.body.dataset.hseLang=l;tr(l);let b=document.getElementById('hse-lang-btn');if(b)b.textContent=l==='ar'?'EN':'عربي'}
function controls(){if(document.getElementById('hse-global-controls'))return;let w=document.createElement('div');w.id='hse-global-controls';w.innerHTML='<button id="hse-lang-btn" type="button">عربي</button><button id="hse-theme-btn" type="button">🌙 Dark</button>';let host=document.querySelector('.unified-meta,.header-actions,.user');if(host)host.appendChild(w);else document.body.appendChild(w);document.getElementById('hse-lang-btn').onclick=()=>{localStorage.setItem('alfaLabsLang',(localStorage.getItem('alfaLabsLang')||'en')==='en'?'ar':'en');lang()};document.getElementById('hse-theme-btn').onclick=()=>{localStorage.setItem('alfaLabsTheme',(localStorage.getItem('alfaLabsTheme')||'light')==='light'?'dark':'light');theme()}}
function style(){if(document.getElementById('hse-global-ui-style'))return;let s=document.createElement('style');s.id='hse-global-ui-style';s.textContent=`
#hse-global-controls{display:flex;align-items:center;gap:6px;margin-left:6px;direction:ltr;flex:0 0 auto}#hse-global-controls button{border:1px solid #d8e2ec;background:#f6f9fc;color:#17365d;border-radius:9px;padding:8px 10px;font:800 11px Arial;cursor:pointer;white-space:nowrap;transition:.18s}#hse-global-controls button:hover{transform:translateY(-1px);background:#fff}
html.hse-dark body{background:#0b1522!important;color:#e4edf7!important}html.hse-dark .unified-header,html.hse-dark .header,html.hse-dark .topbar{background:#101d2c!important;border-color:#26394d!important}html.hse-dark .unified-title h1,html.hse-dark .unified-title h2,html.hse-dark .header h2,html.hse-dark .title h1{color:#eaf2fb!important}html.hse-dark .unified-title p,html.hse-dark .header p,html.hse-dark .title p,html.hse-dark .update-status,html.hse-dark .live-clock{color:#b8c8d8!important}html.hse-dark .live-clock,html.hse-dark .date-box{background:#172638!important;border-color:#2a4056!important}
html.hse-dark .card,html.hse-dark .filters,html.hse-dark .filters-card,html.hse-dark .table-card,html.hse-dark .data-status,html.hse-dark .quick a,html.hse-dark .action,html.hse-dark .snapshot{background:#111f2f!important;border-color:#2a3e53!important;color:#e4edf7!important;box-shadow:0 8px 22px rgba(0,0,0,.2)!important}html.hse-dark .card-title h3,html.hse-dark .section-head h3,html.hse-dark .table-head h3,html.hse-dark .chart-card h3,html.hse-dark .filters h3{color:#eaf2fb!important}html.hse-dark .card-title span,html.hse-dark .welcome p,html.hse-dark .data-status,html.hse-dark .kpi-sub,html.hse-dark .chart-note,html.hse-dark .field label,html.hse-dark .count{color:#aebfd0!important}
html.hse-dark input,html.hse-dark select,html.hse-dark textarea,html.hse-dark .searchbox,html.hse-dark .custom-btn,html.hse-dark .date{background:#0e1a28!important;color:#e7eff8!important;border-color:#344b61!important}html.hse-dark .dropdown{background:#0f1d2c!important;border-color:#344b61!important}html.hse-dark .option:hover,html.hse-dark .option.selected{background:#1c3a59!important;color:#fff!important}html.hse-dark table th{background:#143a5e!important;color:#fff!important}html.hse-dark table td{border-color:#283d51!important;color:#dce7f2!important}html.hse-dark tr:hover td{background:#16283b!important}html.hse-dark .table-scroll{border-color:#2a3e53!important}html.hse-dark .footer{background:#07182a!important;border-color:#294057!important}html.hse-dark .donut-inner{background:#111f2f!important;color:#eaf2fb!important}
html.hse-dark .btn-light,html.hse-dark .clear{background:#172638!important;color:#dbe7f2!important;border-color:#344b61!important}html.hse-dark .modal-box{background:#101e2d!important;color:#e6eef7!important}html.hse-dark .detail{background:#172638!important}html.hse-dark .detail-label{color:#aebfd0!important}html.hse-dark .detail-value{color:#e7eef7!important}html.hse-dark #hse-global-controls button{background:#172638!important;color:#e7eef7!important;border-color:#344b61!important}
html[data-hse-lang="ar"] .content,html[data-hse-lang="ar"] .banner,html[data-hse-lang="ar"] .hero,html[data-hse-lang="ar"] .filters,html[data-hse-lang="ar"] .filters-card,html[data-hse-lang="ar"] .table-card{text-align:right}html[data-hse-lang="ar"] .unified-title,html[data-hse-lang="ar"] .title{text-align:right}html[data-hse-lang="ar"] .field label,html[data-hse-lang="ar"] th{text-align:right}
@media(max-width:800px){#hse-global-controls{gap:4px;margin-left:0}#hse-global-controls button{padding:6px 7px;font-size:9px}}@media(max-width:430px){#hse-global-controls button{padding:5px 6px;font-size:8px}}
`;document.head.appendChild(s)}
function init(){style();controls();theme();lang();new MutationObserver(m=>{if(m.some(x=>x.addedNodes?.length))setTimeout(lang,0)}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
window.AlfaHSEGlobal={theme,lang,charts,M};
})();