/* Alfa Labs HSE — Global UI Standard */
(function(){
'use strict';if(window.__ALFA_GLOBAL_UI__)return;window.__ALFA_GLOBAL_UI__=true;
const M=Object.fromEntries([
['Home','الرئيسية'],['MAIN','الرئيسية'],['SYSTEM','النظام'],['Training','التدريب'],['Safety Observations','ملاحظات السلامة'],['Incidents','الحوادث'],['Near Miss','شبه الحوادث'],['Inspections','التفتيشات'],['Fire Safety','سلامة الحريق'],['First Aid','الإسعافات الأولية'],['Analytics','التحليلات'],['Reports','التقارير'],['Settings','الإعدادات'],
['HSE Management Dashboard','لوحة إدارة السلامة والصحة المهنية والبيئة'],['Alfa Labs HSE Management Platform','منصة ألفا لابز لإدارة السلامة والصحة المهنية والبيئة'],['Alfa Labs • HSE Platform','ألفا لابز • منصة السلامة والصحة المهنية والبيئة'],['Last updated today','آخر تحديث اليوم'],
['Executive HSE Overview','نظرة تنفيذية على أداء HSE'],['CAPA performance and Training activity in one clear management view.','أداء CAPA ونشاط التدريب في لوحة إدارية واضحة.'],['LIVE DATA • ALFA LABS','بيانات مباشرة • ألفا لابز'],['HSE Performance 👋','أداء HSE 👋'],['Key indicators and management actions at a glance','المؤشرات الرئيسية وإجراءات الإدارة في نظرة واحدة'],['HSE PERFORMANCE — LIVE','أداء HSE — مباشر'],
['Total CAPA','إجمالي CAPA'],['Open CAPA','CAPA المفتوحة'],['High Risk','مخاطر عالية'],['Critical','حرج'],['Training Sessions','جلسات التدريب'],['Training Hours','ساعات التدريب'],['All CAPA records','جميع سجلات CAPA'],['Requires corrective action','تتطلب إجراءً تصحيحياً'],['Priority CAPA','CAPA ذات الأولوية'],['Management attention','تحتاج اهتمام الإدارة'],['Actual dated records','السجلات المؤرخة'],['Recorded training hours','ساعات التدريب المسجلة'],['View CAPA →','عرض CAPA ←'],['Filter Open →','تصفية المفتوحة ←'],['Filter High →','تصفية العالية ←'],['Filter Critical →','تصفية الحرجة ←'],['View Training →','عرض التدريب ←'],['Training analytics →','تحليلات التدريب ←'],
['CAPA Risk Profile','ملف مخاطر CAPA'],['Current distribution','التوزيع الحالي'],['CAPA Status','حالة CAPA'],['Live','مباشر'],['Open','مفتوحة'],['In Progress','قيد التنفيذ'],['Closed','مغلقة'],['Training Trend','اتجاه التدريب'],['Sessions by month','الجلسات حسب الشهر'],['Training Mix','توزيع التدريب'],['Top training types','أعلى أنواع التدريب'],['Action Required','إجراء مطلوب'],['Priority management view','عرض الإدارة حسب الأولوية'],['Immediate management attention','اهتمام إداري فوري'],['Priority corrective action','إجراء تصحيحي ذو أولوية'],['Still requiring closure','ما زال يتطلب الإغلاق'],
['Employees trained','الموظفون الذين تم تدريبهم'],['Departments covered','الإدارات المشمولة'],['Training programs','البرامج التدريبية'],['Training providers','جهات التدريب'],['Add CAPA','إضافة CAPA'],['Get a Report','الحصول على تقرير'],
['CAPA — Management Analysis','CAPA — التحليل الإداري'],['Same dashboard visual language | management-level CAPA profile','نفس الهوية البصرية للوحة | تحليل CAPA على مستوى الإدارة'],['CAPA — Detailed Distribution','CAPA — التوزيع التفصيلي'],['Additional management breakdown | same live CAPA dataset','تفصيل إداري إضافي | نفس بيانات CAPA المباشرة'],['CAPA Records by Month','سجلات CAPA حسب الشهر'],['Top CAPA Sites','أعلى مواقع CAPA'],['CAPA by Governorate','CAPA حسب المحافظة'],['Top CAPA Owners','أعلى مسؤولي CAPA'],
['Training — Management Analysis','التدريب — التحليل الإداري'],['Same dashboard visual language | training coverage and delivery','نفس الهوية البصرية للوحة | تغطية وتنفيذ التدريب'],['Management Summary & Actions','الملخص الإداري والإجراءات'],['Executive reference | generated directly from live dashboard data','مرجع تنفيذي | مُنشأ مباشرة من بيانات اللوحة'],['Executive Highlights','أبرز النتائج التنفيذية'],['Management Actions','الإجراءات الإدارية'],
['Prioritize Critical and High CAPA closure.','إعطاء أولوية لإغلاق CAPA الحرجة والعالية.'],['Review open CAPA ageing and overdue ownership.','مراجعة أعمار CAPA المفتوحة والمسؤوليات المتأخرة.'],['Maintain monthly training coverage by department.','الحفاظ على تغطية التدريب الشهرية حسب الإدارة.'],['Use site and department filters for targeted follow-up.','استخدام مرشحات الموقع والإدارة للمتابعة المستهدفة.'],
['Training Management','إدارة التدريب'],['Training Record & HSE Training Analytics','سجلات التدريب وتحليلات HSE'],['Training Management & Analytics','إدارة التدريب والتحليلات'],['Analyze the complete Training Record using Year, Month, From Date and To Date filters.','تحليل سجل التدريب باستخدام مرشحات السنة والشهر ومن تاريخ وإلى تاريخ.'],['Time Filters','مرشحات الوقت'],['Year','السنة'],['All Years','كل السنوات'],['Month','الشهر'],['All Months','كل الشهور'],['January','يناير'],['February','فبراير'],['March','مارس'],['April','أبريل'],['May','مايو'],['June','يونيو'],['July','يوليو'],['August','أغسطس'],['September','سبتمبر'],['October','أكتوبر'],['November','نوفمبر'],['December','ديسمبر'],['From Date','من تاريخ'],['To Date','إلى تاريخ'],['Apply Filters','تطبيق المرشحات'],['Reset','إعادة تعيين'],
['Employees Trained','الموظفون المدربون'],['Departments','الإدارات'],['Training Programs','البرامج التدريبية'],['Training Providers','جهات التدريب'],['Employee Status','حالة الموظف'],['Training Type','نوع التدريب'],['Department','الإدارة'],['Job Title','المسمى الوظيفي'],['Training Program','البرنامج التدريبي'],['Training Provider','جهة التدريب'],['Site','الموقع'],['Governorate','المحافظة'],['City','المدينة'],['Area','المنطقة'],['Lab Code','كود المعمل'],['Training Records','سجلات التدريب'],['records','سجلات'],['Training Type 2','نوع التدريب 2'],['Duration (Hours)','المدة (بالساعات)'],['Trainer Notes','ملاحظات المدرب'],['Trainer Name','اسم المدرب'],['Training Date','تاريخ التدريب'],['Employee ID','الرقم الوظيفي'],['Employee Name','اسم الموظف'],['Provider','جهة التدريب'],['Area Name','اسم المنطقة'],['Site Name','اسم الموقع'],
['CAPA Records','سجلات CAPA'],['CAPA Management','إدارة CAPA'],['CAPA Filters','مرشحات CAPA'],['Search','بحث'],['Clear','مسح'],['Save CAPA','حفظ CAPA'],['Cancel','إلغاء'],['Select','اختيار'],['Due Date','تاريخ الاستحقاق'],['Risk Severity','درجة المخاطر'],['Status','الحالة'],['Observation','الملاحظة'],['Hazards Types','أنواع المخاطر'],['Hazard Details','تفاصيل الخطر'],['Corrective Action','الإجراء التصحيحي'],['Owner','المسؤول'],['Code','الكود'],['Site License','ترخيص الموقع'],['HSE Responsibility','مسؤولية HSE'],
['Safety First • Safety Is Everyone’s Responsibility','السلامة أولاً • السلامة مسؤولية الجميع'],['Created','تم الإنشاء'],['Created by Hossam Elsharabasy — HSE Manager','تم الإنشاء بواسطة حسام الشراباسي — مدير HSE'],['Today','اليوم'],['Environment','البيئة'],['Central Lab Only','المعمل المركزي فقط'],['Central Lab','المعمل المركزي'],['Medical Waste Management','إدارة النفايات الطبية'],['Central Lab environmental data • Medical waste transfer and handover register','بيانات البيئة للمعمل المركزي • سجل تسليم وتسلم النفايات الطبية'],['Filters','المرشحات'],['Day','اليوم'],['Month','الشهر'],['Year','السنة'],['Company','الشركة'],['Waste Type','نوع المخلف'],['All Days','كل الأيام'],['All Months','كل الشهور'],['All Years','كل السنوات'],['All Companies','كل الشركات'],['All Waste Types','كل أنواع المخلفات'],['Apply Filters','تطبيق المرشحات'],['Reset','إعادة تعيين'],['Environmental Summary','الملخص البيئي'],['Source: Central Lab register','المصدر: سجل المعمل المركزي'],['Total Waste Weight','إجمالي وزن المخلفات'],['Records','السجلات'],['Bags / Containers','الأكياس / العبوات'],['Safety Boxes','صناديق الأمان'],['Environmental Analysis','التحليل البيئي'],['Based on filtered records','بناءً على السجلات المفلترة'],['Waste by Type','المخلفات حسب النوع'],['Waste by Floor','المخلفات حسب الدور'],['Waste by Company','المخلفات حسب الشركة'],['Movement Type','نوع الحركة'],['Waste Transfer Register','سجل تسليم وتسلم النفايات'],['All source fields retained','تم الاحتفاظ بكل حقول المصدر'],['Data scope: Central Lab only. The dashboard uses the uploaded register as its source and does not add records that are not present in the register.','نطاق البيانات: المعمل المركزي فقط. تستخدم اللوحة السجل المرفوع كمصدر للبيانات ولا تضيف سجلات غير موجودة في السجل.'],['Open Environment Dashboard →','فتح لوحة البيئة ←'],['Total Waste Weight','إجمالي وزن المخلفات'],['Waste Records','سجلات المخلفات'],['Bags / Containers','الأكياس / العبوات'],['Safety Boxes','صناديق الأمان'],['Environment Report — Central Lab','تقرير البيئة — المعمل المركزي'],['Filtered Register Summary','ملخص السجل المفلتر'],['kg','كجم'],['handover records','سجلات التسليم'],['reported quantity','الكمية المسجلة'],['No data for the selected filters.','لا توجد بيانات للفلاتر المحددة.'],['No records found.','لا توجد سجلات.'],['Source: Environment Register','المصدر: سجل البيئة'],['Central Lab • Source: Environment Register','المعمل المركزي • المصدر: سجل البيئة'],['Record','سجل'],['Preparing report…','جاري إعداد التقرير…'],['Report created successfully.','تم إنشاء التقرير بنجاح.'],['Report generation failed.','فشل إنشاء التقرير.']
]);
const norm=s=>String(s??'').replace(/\s+/g,' ').trim(),orig=new WeakMap();
function translate(lang,root=document.body){
 const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement&&/^(SCRIPT|STYLE|CANVAS)$/.test(n.parentElement.tagName)?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}),nodes=[];while(w.nextNode())nodes.push(w.currentNode);
 nodes.forEach(n=>{let raw=orig.has(n)?orig.get(n):n.nodeValue;if(!orig.has(n))orig.set(n,raw);let k=norm(raw);if(!k||/^[-–—•·\d\s,.:/()+%]+$/.test(k))return;if(M[k])n.nodeValue=lang==='ar'?M[k]:k});
 root.querySelectorAll('[placeholder],[title],[aria-label]').forEach(e=>['placeholder','title','aria-label'].forEach(a=>{let v=e.getAttribute(a),k=norm(v);if(v&&M[k])e.setAttribute(a,lang==='ar'?M[k]:k)}));
 root.querySelectorAll('option').forEach(e=>{let raw=e.dataset.hseOriginal||(e.dataset.hseOriginal=e.textContent),k=norm(raw);if(M[k])e.textContent=lang==='ar'?M[k]:k});
}
function chartTheme(dark){
 try{if(!window.Chart)return;Chart.defaults.color=dark?'#d4e1ee':'#536579';Chart.defaults.borderColor=dark?'#31465d':'#dce5ee';
 if(window.charts)Object.values(window.charts).forEach(c=>{if(!c)return;c.options.color=dark?'#d4e1ee':'#536579';if(c.options.scales)Object.values(c.options.scales).forEach(s=>{s.ticks=s.ticks||{};s.ticks.color=dark?'#cbd8e7':'#536579';s.grid=s.grid||{};s.grid.color=dark?'rgba(255,255,255,.10)':'rgba(80,100,120,.12)'});if(c.options.plugins?.legend)c.options.plugins.legend.labels={...(c.options.plugins.legend.labels||{}),color:dark?'#d4e1ee':'#536579'};c.update('none')})}catch(e){}
}
function applyTheme(){let dark=localStorage.getItem('alfaLabsTheme')==='dark';document.documentElement.classList.toggle('hse-dark',dark);document.body.dataset.hseTheme=dark?'dark':'light';let b=document.getElementById('hse-theme-btn');if(b)b.textContent=dark?'☀️ Light':'🌙 Dark';chartTheme(dark);window.dispatchEvent(new CustomEvent('hseThemeChanged',{detail:{dark}}))}
function applyLang(){let lang=localStorage.getItem('alfaLabsLang')||'en';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.dataset.hseLang=lang;translate(lang);let b=document.getElementById('hse-lang-btn');if(b)b.textContent=lang==='ar'?'EN':'عربي'}
function addControls(){if(document.getElementById('hse-global-controls'))return;let w=document.createElement('div');w.id='hse-global-controls';w.innerHTML='<button id="hse-lang-btn" type="button">عربي</button><button id="hse-theme-btn" type="button">🌙 Dark</button>';let host=document.querySelector('.unified-meta,.header-actions,.user');if(host)host.appendChild(w);else document.body.appendChild(w);let b=document.getElementById('hse-lang-btn');b.onclick=()=>{localStorage.setItem('alfaLabsLang',(localStorage.getItem('alfaLabsLang')||'en')==='en'?'ar':'en');applyLang()};document.getElementById('hse-theme-btn').onclick=()=>{localStorage.setItem('alfaLabsTheme',(localStorage.getItem('alfaLabsTheme')||'light')==='light'?'dark':'light');applyTheme()};addWeather()}
async function addWeather(){if(document.getElementById('alfa-weather'))return;const host=document.querySelector('.unified-meta,.header-actions,.user');if(!host)return;const box=document.createElement('div');box.id='alfa-weather';box.innerHTML='<span class="wx-icon">🌙</span><span><span class="wx-temp">--°C</span><br><span class="wx-place">Cairo, Egypt</span></span><span class="wx-extra">Updating…</span>';host.insertBefore(box,host.firstChild);async function load(){try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=30.0444&longitude=31.2357&current=temperature_2m,apparent_temperature,precipitation,rain,showers,snowfall,weather_code,wind_speed_10m,wind_direction_10m&timezone=Africa%2FCairo',{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json(),x=d.current||{},temp=Math.round(Number(x.temperature_2m)),code=Number(x.weather_code||0),rain=Number(x.rain||0)+Number(x.showers||0),wind=Math.round(Number(x.wind_speed_10m||0));const icon=(code>=51&&code<=67)||(code>=80&&code<=82)?'🌧️':(code>=95?'⛈️':(code>=1&&code<=3?'⛅':'☀️'));const period=(new Date()).getHours()>=18||(new Date()).getHours()<6?'🌙':'☀️';box.querySelector('.wx-icon').textContent=period+' '+icon;box.querySelector('.wx-temp').textContent=temp+'°C';let extra=wind+' km/h';if(rain>0)extra+=' • 🌧️ '+rain.toFixed(1)+' mm';box.querySelector('.wx-extra').textContent=extra;}catch(e){box.querySelector('.wx-extra').textContent='Weather unavailable'}}load();setInterval(load,15*60*1000)}
function style(){if(document.getElementById('hse-global-ui-style'))return;let s=document.createElement('style');s.id='hse-global-ui-style';s.textContent=`
#hse-global-controls{display:flex;align-items:center;gap:9px;margin-left:8px;position:relative;z-index:2;direction:ltr;flex:0 0 auto}#hse-global-controls button{border:1px solid #cbd9e6;background:#f6f9fc;color:#17365d;border-radius:11px;padding:10px 14px;min-width:72px;min-height:40px;font:800 13px Arial;cursor:pointer;white-space:nowrap;transition:.18s;box-shadow:0 2px 7px rgba(20,55,90,.10)}#hse-global-controls button:hover{transform:translateY(-1px);background:#fff;border-color:#aebfd0;box-shadow:0 4px 12px rgba(20,55,90,.14)}\n#hse-global-controls #hse-lang-btn{font-weight:900;font-size:14px;letter-spacing:.1px;text-shadow:0 0 .3px currentColor}
html.hse-dark body{background:#0b1522!important;color:#e4edf7!important}html.hse-dark .unified-header,html.hse-dark .header,html.hse-dark .topbar{background:#101d2c!important;border-color:#26394d!important}html.hse-dark .unified-title h1,html.hse-dark .unified-title h2,html.hse-dark .header h2,html.hse-dark .title h1{color:#eaf2fb!important}html.hse-dark .unified-title p,html.hse-dark .header p,html.hse-dark .title p,html.hse-dark .update-status,html.hse-dark .live-clock{color:#b8c8d8!important}html.hse-dark .live-clock,html.hse-dark .date-box{background:#172638!important;border-color:#2a4056!important}
html.hse-dark .kpi{background:#142337!important;color:#eef6ff!important}html.hse-dark .card,html.hse-dark .filters,html.hse-dark .filters-card,html.hse-dark .table-card,html.hse-dark .data-status,html.hse-dark .quick a,html.hse-dark .action,html.hse-dark .snapshot{background:#111f2f!important;border-color:#2a3e53!important;color:#e4edf7!important;box-shadow:0 8px 22px rgba(0,0,0,.2)!important}html.hse-dark .card-title h3,html.hse-dark .section-head h3,html.hse-dark .table-head h3,html.hse-dark .chart-card h3,html.hse-dark .filters h3{color:#eaf2fb!important}html.hse-dark .card-title span,html.hse-dark .welcome p,html.hse-dark .data-status,html.hse-dark .kpi-sub,html.hse-dark .chart-note,html.hse-dark .field label,html.hse-dark .count{color:#aebfd0!important}
html.hse-dark input,html.hse-dark select,html.hse-dark textarea,html.hse-dark .searchbox,html.hse-dark .custom-btn,html.hse-dark .date{background:#0e1a28!important;color:#e7eff8!important;border-color:#344b61!important}html.hse-dark .dropdown{background:#0f1d2c!important;border-color:#344b61!important}html.hse-dark .option:hover,html.hse-dark .option.selected{background:#1c3a59!important;color:#fff!important}html.hse-dark table th{background:#143a5e!important;color:#fff!important}html.hse-dark table td{border-color:#283d51!important;color:#dce7f2!important}html.hse-dark tr:hover td{background:#16283b!important}html.hse-dark .table-scroll{border-color:#2a3e53!important}html.hse-dark .footer{background:#07182a!important;border-color:#294057!important}html.hse-dark .donut-inner{background:#111f2f!important;color:#eaf2fb!important}
html.hse-dark .btn-light,html.hse-dark .clear{background:#172638!important;color:#dbe7f2!important;border-color:#344b61!important}html.hse-dark .modal-box{background:#101e2d!important;color:#e6eef7!important}html.hse-dark .detail{background:#172638!important}html.hse-dark .detail-label{color:#aebfd0!important}html.hse-dark .detail-value{color:#e7eef7!important}html.hse-dark #hse-global-controls button{background:#172638!important;color:#e7eef7!important;border-color:#344b61!important}
/* Premium motion layer — preserves Alfa Labs visual identity */
html:not(.hse-reduced-motion) body::before{content:"";position:fixed;z-index:-1;inset:-25%;pointer-events:none;background:radial-gradient(circle at 18% 22%,rgba(25,118,210,.14),transparent 24%),radial-gradient(circle at 82% 68%,rgba(229,37,42,.08),transparent 22%);animation:alfaAmbient 14s ease-in-out infinite alternate}
html:not(.hse-reduced-motion) body::after{content:"";position:fixed;z-index:-1;inset:0;pointer-events:none;background:linear-gradient(115deg,transparent 0%,rgba(255,255,255,.035) 48%,transparent 52%);background-size:220% 100%;animation:alfaSheen 11s linear infinite}
html:not(.hse-reduced-motion) .unified-header,html:not(.hse-reduced-motion) .header,html:not(.hse-reduced-motion) .topbar,html:not(.hse-reduced-motion) .card,html:not(.hse-reduced-motion) .kpi,html:not(.hse-reduced-motion) .filters,html:not(.hse-reduced-motion) .filters-card,html:not(.hse-reduced-motion) .table-card,html:not(.hse-reduced-motion) .chart-card,html:not(.hse-reduced-motion) .action,html:not(.hse-reduced-motion) .snapshot,html:not(.hse-reduced-motion) .quick a{animation:alfaRise .55s cubic-bezier(.2,.7,.2,1) both}
html:not(.hse-reduced-motion) .kpi{transition:transform .22s ease,box-shadow .22s ease,border-color .22s ease}
html:not(.hse-reduced-motion) .kpi:hover{transform:translateY(-5px);box-shadow:0 14px 30px rgba(20,55,90,.16)}
html:not(.hse-reduced-motion) .card:hover,html:not(.hse-reduced-motion) .chart-card:hover,html:not(.hse-reduced-motion) .table-card:hover{box-shadow:0 14px 34px rgba(20,55,90,.12)}
html:not(.hse-reduced-motion) button:not(:disabled),html:not(.hse-reduced-motion) a{transition:transform .18s ease,box-shadow .18s ease,filter .18s ease}
html:not(.hse-reduced-motion) button:not(:disabled):hover,html:not(.hse-reduced-motion) a:hover{filter:brightness(1.03)}
html:not(.hse-reduced-motion) .live-clock{animation:alfaPulse 2.8s ease-in-out infinite}
html:not(.hse-reduced-motion) #hse-global-controls button{position:relative;overflow:hidden}
html:not(.hse-reduced-motion) #hse-global-controls button::after{content:"";position:absolute;inset:0;transform:translateX(-120%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.22),transparent);animation:alfaButtonShine 5s ease-in-out infinite}
@keyframes alfaAmbient{from{transform:translate3d(-2%, -1%,0) scale(1)}to{transform:translate3d(2%, 2%,0) scale(1.06)}}
@keyframes alfaSheen{0%{background-position:220% 0}100%{background-position:-220% 0}}
@keyframes alfaRise{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}
@keyframes alfaPulse{0%,100%{box-shadow:0 0 0 0 rgba(25,118,210,.08)}50%{box-shadow:0 0 0 7px rgba(25,118,210,.03)}}
@keyframes alfaButtonShine{0%,65%,100%{transform:translateX(-120%)}82%{transform:translateX(120%)}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto!important}html body::before,html body::after,html .live-clock,html #hse-global-controls button::after{animation:none!important}html .card,html .kpi,html .chart-card,html .table-card,html .action,html .snapshot,html .quick a{animation:none!important;transform:none!important}}

/* Premium dark-mode depth */
html.hse-dark:not(.hse-reduced-motion) .card,html.hse-dark:not(.hse-reduced-motion) .kpi,html.hse-dark:not(.hse-reduced-motion) .chart-card,html.hse-dark:not(.hse-reduced-motion) .table-card{box-shadow:0 12px 32px rgba(0,0,0,.24)}
html.hse-dark:not(.hse-reduced-motion) .kpi:hover{box-shadow:0 18px 38px rgba(0,0,0,.34)}

/* Weather + dark/light contrast controls */
html:not(.hse-dark) #hse-global-controls #hse-theme-btn{background:#0b3157!important;color:#fff!important;border-color:#0b3157!important}
html.hse-dark #hse-global-controls #hse-theme-btn{background:#fff!important;color:#071a2e!important;border-color:#fff!important}
#alfa-weather{display:flex;align-items:center;gap:8px;background:#f5f7fa;border:1px solid #e3eaf1;border-radius:10px;padding:8px 11px;color:#17365d;font-size:11px;font-weight:800;white-space:nowrap;direction:ltr}
#alfa-weather .wx-icon{font-size:19px;line-height:1}#alfa-weather .wx-temp{font-size:15px;font-weight:900}#alfa-weather .wx-place{font-size:10px;color:#71808e;font-weight:700}#alfa-weather .wx-extra{font-size:10px;color:#536b83}
html.hse-dark #alfa-weather{background:#172638!important;border-color:#344b61!important;color:#e7eff8!important}html.hse-dark #alfa-weather .wx-place,html.hse-dark #alfa-weather .wx-extra{color:#b8c8d8!important}
html[data-hse-lang="ar"] #alfa-weather{direction:rtl}
@media(max-width:800px){.unified-header{padding-top:16px!important;padding-bottom:16px!important}.unified-title{padding-top:3px!important}.unified-title h1,.unified-title h2{overflow:visible!important;text-overflow:clip!important;white-space:normal!important;line-height:1.25!important}#alfa-weather{padding:6px 8px;gap:5px}#alfa-weather .wx-temp{font-size:13px}#alfa-weather .wx-place{font-size:8px}#alfa-weather .wx-extra{font-size:8px}}
@media(max-width:430px){.unified-header{padding-top:14px!important;padding-bottom:14px!important}.unified-title{padding-top:4px!important}.unified-title h1,.unified-title h2{line-height:1.2!important}#alfa-weather{max-width:155px}.wx-extra{display:none!important}}
\nhtml[data-hse-lang="ar"] .content,html[data-hse-lang="ar"] .banner,html[data-hse-lang="ar"] .hero,html[data-hse-lang="ar"] .filters,html[data-hse-lang="ar"] .filters-card,html[data-hse-lang="ar"] .table-card{text-align:right}html[data-hse-lang="ar"] .unified-title,html[data-hse-lang="ar"] .title{text-align:right}html[data-hse-lang="ar"] .field label,html[data-hse-lang="ar"] th{text-align:right}
@media(max-width:800px){#hse-global-controls{gap:7px;margin-left:0}#hse-global-controls button{padding:9px 11px;min-width:66px;min-height:38px;font-size:12px;border-radius:10px}}@media(max-width:430px){#hse-global-controls{gap:5px}#hse-global-controls button{padding:8px 9px;min-width:60px;min-height:36px;font-size:11px}}
`;document.head.appendChild(s)}
function init(){style();addControls();applyTheme();applyLang();new MutationObserver(m=>{if(m.some(x=>x.addedNodes?.length))setTimeout(applyLang,0)}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.AlfaHSEGlobal={applyTheme,applyLang,chartTheme,M};
})();